### PR TITLE
Update LEPTON_SDK.c

### PR DESCRIPTION
**Pull request by mellbratt**
Had to make these small changes for it to compile on macOS Catalina 10.15.7 and Qt 5.15.2

### CODE REVIEW

**Comment by kekiefer** [comment]
Hi! Thanks for the PR.

I believe that this change is syntactically correct, but it appears like it will create an infinite recursion at runtime when the function calls itself.

The `LEP_GetAttribute` function still needs to call the "concrete" implementation of `UVC_GetAttribute`, defined in `src/leptonvariation.cpp`, which does the actual communication with the device.

If you provide the compile error message, I might be able to offer a bit more help.

**Comment by mellbratt** [comment]
Oops,

Yes I'm new at this. ;D Did as suggested in the error message below and it would then run. Didn't realise it would cause other problems...

`
/Users/xxxxx/Downloads/GetThermal-master/lepton_sdk/Src/LEPTON_SDK.c:142: error: implicit declaration of function 'UVC_GetAttribute' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
../GetThermal-master/lepton_sdk/Src/LEPTON_SDK.c:142:18: error: implicit declaration of function 'UVC_GetAttribute' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        result = UVC_GetAttribute(portDescPtr, commandID, attributePtr, attributeWordLength);
                 ^
../GetThermal-master/lepton_sdk/Src/LEPTON_SDK.c:142:18: note: did you mean 'LEP_GetAttribute'?
../GetThermal-master/lepton_sdk/Src/LEPTON_SDK.c:102:12: note: 'LEP_GetAttribute' declared here
LEP_RESULT LEP_GetAttribute(LEP_CAMERA_PORT_DESC_T_PTR portDescPtr,
           ^
`
